# Generated by Django 5.2.4 on 2025-07-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='is_accepted',
            new_name='is_both_accepted',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='receiver',
            new_name='receiver_user',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='name',
            new_name='room_name',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='sender',
            new_name='sender_user',
        ),
    ]
