# Generated by Django 5.2.4 on 2025-07-19 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_chatroom_chatroomx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoomX',
            new_name='ChatRoom',
        ),
    ]
