# Generated by Django 5.2.4 on 2025-07-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_chatroom_users_chatroom_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
