# Generated by Django 5.2.4 on 2025-07-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('core', '0004_remove_chatroom_is_accepted_and_more'),
    ]

    operations = [
    ]
